#src/main/resources/META-INF/resources/WEB-INF/jsp/sayHello.jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    org:
      springframework: debug
    com:
      example:
        webapp1: info
